name: Build maven project

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: cache-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            cache-maven-

      - name: Build with Maven
        run: ./mvnw clean deploy -s $GITHUB_WORKSPACE/settings.xml --batch-mode
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
