name: Build maven project

on:
  pull_request:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.event.ref, 'refs/tags/v') && 'sonatype' || null }}
    permissions:
      contents: read
      packages: write
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: cache-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            cache-maven-
      - name: Build
        run: ./mvnw --batch-mode clean package
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
      - name: Publish Maven packages
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: ./mvnw --batch-mode deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
